import { spawn } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

const targetUrl=process.env.HUNTER_REVIEW_URL;if(!targetUrl)throw new Error('HUNTER_REVIEW_URL is required');
const outDir=process.env.PROOF_DIR||'artifacts/hunter-chat-menu-touch';await mkdir(outDir,{recursive:true});
const chromePath=[process.env.CHROME_PATH,'/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/usr/bin/chromium'].filter(Boolean).find(existsSync);if(!chromePath)throw new Error('Chrome missing');
const port=9251;const chrome=spawn(chromePath,['--headless=new','--no-sandbox','--disable-gpu',`--remote-debugging-port=${port}`,`--user-data-dir=${join(process.env.RUNNER_TEMP||'/tmp',`srg-chat-menu-${Date.now()}`)}`,'--window-size=390,844','about:blank'],{stdio:['ignore','pipe','pipe']});
let log='';chrome.stdout.on('data',d=>log+=String(d));chrome.stderr.on('data',d=>log+=String(d));const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function waitJson(url){for(let i=0;i<120;i++){try{const r=await fetch(url);if(r.ok)return r.json()}catch{}await sleep(250)}throw new Error(log.slice(-4000))}
let ws,id=0;const pending=new Map();function cdp(method,params={}){const n=++id;return new Promise((resolve,reject)=>{pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}))})}
async function evalJs(expression){const r=await cdp('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result?.value}
async function waitFor(expression,label){for(let i=0;i<140;i++){try{if(await evalJs(expression))return}catch{}await sleep(80)}throw new Error(`Timed out ${label}`)}
async function shot(name){const r=await cdp('Page.captureScreenshot',{format:'png',fromSurface:true,captureBeyondViewport:false});await writeFile(join(outDir,name),Buffer.from(r.data,'base64'))}
async function state(stage){return evalJs(`(()=>{const m=document.querySelector('#hcs2Menu'),legacy=document.querySelector('#hcs2Side'),main=document.querySelector('#sidebar'),scrim=document.querySelector('#drawerScrim');const rect=e=>{if(!e)return null;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return{x:r.x,y:r.y,left:r.left,right:r.right,width:r.width,height:r.height,display:s.display,visibility:s.visibility,opacity:s.opacity}};const mr=rect(main),probe=mr?document.elementFromPoint(Math.max(12,Math.min(mr.right-12,120)),Math.max(80,Math.min(mr.bottom-40,160))):null;return{stage:${JSON.stringify(stage)},role:document.querySelector('#roleSelect')?.value||'',htmlClass:document.documentElement.className,menu:rect(m),menuExpanded:m?.getAttribute('aria-expanded')||'',menuOwner:m?.dataset.mobileSidebarOwner||'',menuDirect:m?.dataset.mobileSidebarDirect||'',main:mr,mainOpen:!!main?.classList.contains('open'),mainVisible:!!mr&&mr.display!=='none'&&mr.visibility!=='hidden'&&Number(mr.opacity||1)>0&&mr.width>200&&mr.left>=-1,mainHit:!!probe?.closest?.('#sidebar'),scrimOpen:!!scrim?.classList.contains('open'),legacy:rect(legacy),legacyOpen:!!legacy?.classList.contains('open'),mobileAudit:globalThis.__HUNTER_MOBILE_SIDEBAR_TOUCH_AUDIT__||null,guard:globalThis.__HUNTER_FULL_STANDARD_GUARD_AUDIT__||null,trace:(globalThis.__SRG_CHAT_MENU_TRACE__||[]).slice(-100)}})()`)}
const report={targetUrl,stages:[],startedAt:new Date().toISOString(),requirement:'regular mobile chat opens the permanent visible #sidebar; hidden #hcs2Side must remain closed'};
try{
 const tabs=await waitJson(`http://127.0.0.1:${port}/json/list`),t=tabs.find(x=>x.type==='page')||tabs[0];ws=new WebSocket(t.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.addEventListener('open',resolve,{once:true});ws.addEventListener('error',reject,{once:true})});ws.addEventListener('message',e=>{const m=JSON.parse(String(e.data));if(!m.id||!pending.has(m.id))return;const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(new Error(JSON.stringify(m.error))):p.resolve(m.result||{})});
 await cdp('Runtime.enable');await cdp('Page.enable');
 await cdp('Page.addScriptToEvaluateOnNewDocument',{source:`globalThis.__SRG_CHAT_MENU_TRACE__=[];let seq=0;const ids=new WeakMap(),token=n=>{if(!n)return 0;if(!ids.has(n))ids.set(n,++seq);return ids.get(n)};for(const type of ['pointerdown','touchstart','touchend','pointerup','click'])window.addEventListener(type,e=>{const m=e.target?.closest?.('#hcs2Menu'),main=document.querySelector('#sidebar'),legacy=document.querySelector('#hcs2Side');if(!m&&!e.target?.closest?.('#sidebar,#hcs2Side'))return;globalThis.__SRG_CHAT_MENU_TRACE__.push({type,target:e.target?.id||e.target?.tagName||'',menuToken:token(document.querySelector('#hcs2Menu')),mainToken:token(main),legacyToken:token(legacy),mainOpen:!!main?.classList.contains('open'),legacyOpen:!!legacy?.classList.contains('open'),defaultPrevented:e.defaultPrevented,at:performance.now()})},true);new MutationObserver(ms=>{const main=document.querySelector('#sidebar'),legacy=document.querySelector('#hcs2Side'),m=document.querySelector('#hcs2Menu');globalThis.__SRG_CHAT_MENU_TRACE__.push({type:'mutation',menuToken:token(m),mainToken:token(main),legacyToken:token(legacy),mainOpen:!!main?.classList.contains('open'),legacyOpen:!!legacy?.classList.contains('open'),mutations:ms.map(x=>({type:x.type,target:x.target?.id||x.target?.className||x.target?.tagName,attr:x.attributeName})).slice(0,8),at:performance.now()});if(globalThis.__SRG_CHAT_MENU_TRACE__.length>180)globalThis.__SRG_CHAT_MENU_TRACE__.shift()}).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class','aria-expanded']});`});
 await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:3,mobile:true,screenWidth:390,screenHeight:844});await cdp('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});await cdp('Emulation.setUserAgentOverride',{userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.5 Mobile/15E148 Safari/604.1',platform:'iPhone'});
 await cdp('Page.navigate',{url:`${targetUrl}${targetUrl.includes('?')?'&':'?'}srg-chat-menu=${Date.now()}`});await waitFor("document.readyState==='complete'&&!!document.querySelector('#roleSelect')",'shell');
 await evalJs(`(()=>{const s=document.querySelector('#roleSelect');s.value='regular';s.dispatchEvent(new Event('change',{bubbles:true}));return true})()`);await waitFor("document.querySelector('#page-hunter-chat')?.classList.contains('active')&&!!document.querySelector('#hcs2Menu')&&!!document.querySelector('#sidebar')",'regular chat');await sleep(450);
 report.stages.push(await state('ready'));await shot('01-ready.png');
 const p=await evalJs(`(()=>{const e=document.querySelector('#hcs2Menu'),r=e.getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2}})()`);
 await cdp('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:p.x,y:p.y,radiusX:7,radiusY:7,force:1,id:1}]});await sleep(30);report.stages.push(await state('after-touch-start'));
 await cdp('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await sleep(30);report.stages.push(await state('after-touch-end-30ms'));await sleep(170);report.stages.push(await state('after-200ms'));await sleep(650);report.stages.push(await state('after-850ms'));await shot('02-after-touch.png');
 const successful=report.stages.filter(x=>x.mainOpen&&x.mainVisible&&x.mainHit&&x.scrimOpen&&!x.legacyOpen);report.passed=successful.length>0&&report.stages.at(-1).mainOpen&&report.stages.at(-1).mainVisible&&report.stages.at(-1).mainHit&&report.stages.at(-1).scrimOpen&&!report.stages.at(-1).legacyOpen;report.completedAt=new Date().toISOString();await writeFile(join(outDir,'diagnostic.json'),JSON.stringify(report,null,2));if(!report.passed)throw new Error(`Permanent sidebar did not remain visibly open: ${JSON.stringify(report,null,2)}`);console.log('SRG REGULAR CHAT PERMANENT SIDEBAR PASS');
}catch(error){report.passed=false;report.error=String(error?.stack||error);report.completedAt=new Date().toISOString();await writeFile(join(outDir,'diagnostic.json'),JSON.stringify(report,null,2));try{await shot('99-failure.png')}catch{}throw error}finally{try{ws?.close()}catch{}chrome.kill('SIGTERM');await sleep(250);if(!chrome.killed)chrome.kill('SIGKILL')}
